In [1]:
import pandas as pd
import numpy as np
import time 
from scipy import sparse

In [38]:
def read_sentence(num_files = 1,sentence_i=1, data_path = ""):
    data = []
    if sentence_i == 1:
        path = data_path + 'Embedded Data/'
        for i in range(num_files):
            filename = 'embedded' + str(i+1) +'.npy'
            temp = np.load(path+filename)
            data.extend(temp)
    else:
        path = data_path + 'Embedded Data 2/'
        for i in range(num_files):
            filename = 'embedded' + str(i+41) +'.npy'
            temp = np.load(path+filename)
            data.extend(temp)
    return data

def sparsify_a_vector(sentence_vec,threshold=0.0005):
    'if value in vector is smaller than threshold, set it to 0'
    for i in range(len(sentence_vec)):
        if sentence_vec[i]<threshold:
            sentence_vec[i] = 0
    #sparse matrix
    return sparse.csr_matrix(sentence_vec)

def sparsify_a_sentence(sentence,threshold=0.0005):
    '''Load in a sentence, return a sparse sentence'''
    sparse_sentence = []
    for vector in sentence:
            sparse_sentence.append(sparsify_a_vector(vector,threshold))
    return sparse_sentence

def sparsify_sentences(sentences,threshold=0.0005):
    sparse_sentences = []
    for sentence in sentences:
        sparse_sentences.append(sparsify_a_sentence(sentence,threshold))
    return sparse_sentences

In [40]:
t = time.time()
data = read_sentence()
print (time.time()-t)

1.1230180263519287


In [19]:
sparsify_a_vector(data[0][0])

<1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 362 stored elements in Compressed Sparse Row format>

In [24]:
sparsify_a_sentence(data[0])

[<1x4096 sparse matrix of type '<class 'numpy.float32'>'
 	with 362 stored elements in Compressed Sparse Row format>,
 <1x4096 sparse matrix of type '<class 'numpy.float32'>'
 	with 362 stored elements in Compressed Sparse Row format>,
 <1x4096 sparse matrix of type '<class 'numpy.float32'>'
 	with 362 stored elements in Compressed Sparse Row format>,
 <1x4096 sparse matrix of type '<class 'numpy.float32'>'
 	with 362 stored elements in Compressed Sparse Row format>,
 <1x4096 sparse matrix of type '<class 'numpy.float32'>'
 	with 362 stored elements in Compressed Sparse Row format>,
 <1x4096 sparse matrix of type '<class 'numpy.float32'>'
 	with 362 stored elements in Compressed Sparse Row format>,
 <1x4096 sparse matrix of type '<class 'numpy.float32'>'
 	with 362 stored elements in Compressed Sparse Row format>,
 <1x4096 sparse matrix of type '<class 'numpy.float32'>'
 	with 362 stored elements in Compressed Sparse Row format>,
 <1x4096 sparse matrix of type '<class 'numpy.float32'>'

In [57]:
##一个sentence的embedding里面有多少很小的数
cnt=0
for i in range(len(a[0][3])):
    if a[0][3][i] < 0.0005:
        cnt += 1
print(cnt)

3734


# sparsify一个file

In [41]:
## Sparsify one file of sentence embedding
t = time.time()
sparse_sentences_example = sparsify_sentences(data)
print (time.time()-t)

72.9772458076477


In [42]:
len(sparse_sentences_example)

1000

In [43]:
np.save('sparsify_example.npy',sparse_sentences_example)

# 存所有file

In [67]:
def load_one_file(file_idx = 1,sentence_i=1, data_path = ""):
    data = []
    if sentence_i == 1:
        path = data_path + 'Embedded Data/'
        filename = 'embedded' + str(file_idx+1) +'.npy'
        temp = np.load(path+filename)
        data.extend(temp)
    else:
        path = data_path + 'Embedded Data 2/'
        filename = 'embedded' + str(file_idx+41) +'.npy'
        temp = np.load(path+filename)
        data.extend(temp)
    return data


def sparsify_all(num_file = 40, sentence_i = 1, path = "E:\ATEC_data/"):
    t = time.time()
    for i in range(num_file):
        sparsied_file = []
        sentences1 = load_one_file(file_idx = i,sentence_i=1, data_path = path)
        sentences2 = load_one_file(file_idx = i,sentence_i=2, data_path = path)
        sparse_s1 = sparsify_sentences(sentences1)
        sparse_s2 = sparsify_sentences(sentences2)
        np.save(path+'sparse1/'+'sparsed'+str(i+1)+'.npy', sparse_s1)
        np.save(path+'sparse2/'+'sparsed'+str(i+41)+'.npy', sparse_s2)
        print('-------done', i, '-----------')
        print('cost time: ',time.time()-t)

In [72]:
sparsify_all(num_file=40)

-------done 0 -----------
cost time:  139.9421455860138
-------done 1 -----------
cost time:  278.0386085510254
-------done 2 -----------
cost time:  416.764990568161
-------done 3 -----------
cost time:  559.4313673973083
-------done 4 -----------
cost time:  702.3968045711517
-------done 5 -----------
cost time:  842.796172618866
-------done 6 -----------
cost time:  984.2469792366028
-------done 7 -----------
cost time:  1121.8762829303741
-------done 8 -----------
cost time:  1262.0597131252289
-------done 9 -----------
cost time:  1401.0797317028046
-------done 10 -----------
cost time:  1542.6107068061829
-------done 11 -----------
cost time:  1682.1078758239746
-------done 12 -----------
cost time:  1823.4115660190582
-------done 13 -----------
cost time:  1961.410118818283
-------done 14 -----------
cost time:  2099.4978065490723
-------done 15 -----------
cost time:  2236.981304883957
-------done 16 -----------
cost time:  2375.3649230003357
-------done 17 -----------
cost tim

In [69]:
data = np.load("E:/ATEC_data/sparse1/sparsed1.npy")

In [71]:
print(data[0][0])

  (0, 5)	0.0633433
  (0, 40)	0.0436378
  (0, 67)	0.00134987
  (0, 71)	0.0204936
  (0, 88)	0.00203065
  (0, 100)	0.141576
  (0, 108)	0.01896
  (0, 112)	0.0465292
  (0, 116)	0.00951259
  (0, 140)	0.000857676
  (0, 147)	0.00197577
  (0, 172)	0.0233194
  (0, 173)	0.0729285
  (0, 177)	0.0575681
  (0, 180)	0.0116272
  (0, 197)	0.0580731
  (0, 199)	0.0136484
  (0, 201)	0.02696
  (0, 211)	0.0132665
  (0, 221)	0.0310051
  (0, 223)	0.00877503
  (0, 245)	0.0034516
  (0, 250)	0.0162998
  (0, 268)	0.0029015
  (0, 278)	0.00162887
  :	:
  (0, 3837)	0.0418995
  (0, 3842)	0.0106652
  (0, 3845)	0.0295629
  (0, 3846)	0.0195426
  (0, 3882)	0.0186537
  (0, 3889)	0.024887
  (0, 3902)	0.004256
  (0, 3910)	0.00620804
  (0, 3914)	0.0280932
  (0, 3922)	0.0222595
  (0, 3925)	0.0017314
  (0, 3945)	0.0416749
  (0, 3961)	0.00112671
  (0, 3964)	0.0319807
  (0, 3969)	0.00990112
  (0, 3977)	0.00787815
  (0, 3978)	0.0170292
  (0, 3987)	0.019152
  (0, 4011)	0.0205669
  (0, 4016)	0.0241898
  (0, 4018)	0.011957
  (0, 4029

# Load and Operations

In [57]:
data = np.load('sparsify_example.npy')

In [58]:
def sparse_to

D:\Anaconda\lib\site-packages\scipy\sparse\compressed.py:226: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.
  " != instead.", SparseEfficiencyWarning)


array([ [<1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 362 stored elements in Compressed Sparse Row format>, <1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 362 stored elements in Compressed Sparse Row format>, <1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 362 stored elements in Compressed Sparse Row format>, <1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 362 stored elements in Compressed Sparse Row format>, <1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 362 stored elements in Compressed Sparse Row format>, <1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 362 stored elements in Compressed Sparse Row format>, <1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 362 stored elements in Compressed Sparse Row format>, <1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 362 stored elements in Compressed Sparse Row format>, <1x4096 sparse matrix of type '<class 'numpy.float32'>'
	with 3

In [53]:
print(sparse_sentences_example[0][5].toarray())

[[ 0.  0.  0. ...,  0.  0.  0.]]


# Other things

In [88]:
i = 0
filename = 'embedded' + str(i+1) +'.npy'
temp = np.load(path+filename)

In [94]:
temp[0].shape

(11, 4096)

In [95]:
len(temp)

1000

In [96]:
temp[0]

array([[-0.01049833, -0.08939895, -0.03044511, ..., -0.03926745,
        -0.03814264, -0.0289226 ],
       [-0.01049833, -0.08939895, -0.03044511, ..., -0.03926745,
        -0.03814264, -0.0289226 ],
       [-0.01049833, -0.08939895, -0.03044511, ..., -0.03926745,
        -0.03814264, -0.0289226 ],
       ..., 
       [-0.01049833, -0.08939897, -0.03044511, ..., -0.03926746,
        -0.03814263, -0.0289226 ],
       [-0.01049833, -0.08939897, -0.03044511, ..., -0.03926746,
        -0.03814263, -0.0289226 ],
       [-0.01049833, -0.08939897, -0.03044511, ..., -0.03926746,
        -0.03814263, -0.0289226 ]], dtype=float32)

In [97]:
a = 123
[int(i) for i in list(str(a))]

[1, 2, 3]

In [99]:
np.random.rand(4, 5)

array([[ 0.42219615,  0.98160289,  0.16067229,  0.4224422 ,  0.89947799],
       [ 0.47975105,  0.51384139,  0.34674121,  0.175309  ,  0.875707  ],
       [ 0.50221752,  0.42645295,  0.6033981 ,  0.01662318,  0.96231036],
       [ 0.8479314 ,  0.25337405,  0.90811242,  0.00359013,  0.47568747]])

In [100]:
np.random.rand(5, 5)

array([[ 0.20296951,  0.73678942,  0.05478556,  0.25842292,  0.63664221],
       [ 0.2965464 ,  0.57045797,  0.54466937,  0.12972127,  0.93271659],
       [ 0.6256504 ,  0.21277431,  0.45144445,  0.37684203,  0.51436089],
       [ 0.51177904,  0.08598491,  0.93905089,  0.61478414,  0.60427023],
       [ 0.02287823,  0.77311431,  0.24237501,  0.88627407,  0.38734028]])

In [ ]:
def random_generate_train_x(num):
    